const servicesData = {
  services: [
    "Cortes",
    "Tintes",
    "Rayitos",
    "Luces",
    "Mechas",
    "Permanentes",
    "Alaciados",
    "Depilación",
    "Planchado de cejas",
    "Rizado de pestañas",
    "Extensión de pestañas",
    "Manicure",
    "Pedicure",
    "Peinados",
    "Maquillaje",
  ],
  servicePrices: {
    Cortes: 150,
    Tintes: 500,
    Rayitos: 800,
    Luces: 1000,
    Mechas: 1200,
    Permanentes: 600,
    Alaciados: 800,
    Depilación: 300,
    "Planchado de cejas": 200,
    "Rizado de pestañas": 400,
    "Extensión de pestañas": 600,
    Manicure: 250,
    Pedicure: 300,
    Peinados: 400,
    Maquillaje: 500,
  },
  serviceOptions: {
    Cortes: ["Lavado", "Secado", "Peinado"],
    Tintes: ["Decoloración", "Tratamiento", "Peinado"],
    Rayitos: ["Matización", "Tratamiento", "Peinado"],
    Luces: ["Matización", "Tratamiento", "Peinado"],
    Mechas: ["Matización", "Tratamiento", "Peinado"],
    Permanentes: ["Tratamiento", "Peinado"],
    Alaciados: ["Tratamiento", "Peinado"],
    Manicure: ["Diseño", "Gelish", "Acrílico"],
    Pedicure: ["Diseño", "Gelish"],
    Peinados: ["Lavado", "Planchado", "Rizado"],
    Maquillaje: ["Pestañas postizas", "Iluminación extra"],
  },
  optionPrices: {
    Lavado: 50,
    Secado: 50,
    Peinado: 100,
    Decoloración: 200,
    Tratamiento: 150,
    Matización: 100,
    Diseño: 50,
    Gelish: 100,
    Acrílico: 200,
    Planchado: 100,
    Rizado: 150,
    "Pestañas postizas": 100,
    "Iluminación extra": 50,
  },
};

export default servicesData;
