const servicesData = {
  services: [
    "Cortes",
    "Tintes",
    "Rayitos",
    "Luces",
    "Mechas",
    "Permanentes",
    "Alaciados",
    "Depilación",
    "Planchado de cejas",
    "Rizado de pestañas",
    "Extensión de pestañas",
    "Manicure",
    "Pedicure",
    "Peinados",
  ],
  servicePrices: {
    Cortes: 60,
    Depilación: 300,
    "Planchado de cejas": 200,
    "Rizado de pestañas": 400,
    "Extensión de pestañas": 600,
    Manicure: 250,
    Pedicure: 300,
    Peinados: 400,
    Maquillaje: 500,
  },
  variableCosts: {
    Tintes: { Corto: 150, Mediano: 250, Largo: 300, Poco: 100, Mucho: 150 },
    Rayitos: { Corto: 300, Mediano: 390, Largo: 600, Poco: 160, Mucho: 280 },
    Luces: { Corto: 300, Mediano: 390, Largo: 600, Poco: 160, Mucho: 280 },
    Mechas: { Corto: 300, Mediano: 390, Largo: 600, Poco: 160, Mucho: 280 },
    Permanentes: {
      Corto: 300,
      Mediano: 390,
      Largo: 600,
      Poco: 160,
      Mucho: 280,
    },
    Alaciados: { Corto: 300, Mediano: 390, Largo: 600, Poco: 160, Mucho: 280 },
  },
  extraTinteCost: 200,
  serviceOptions: {
    Cortes: ["Lavado"],
    Tintes: ["Decoloración", "Tratamiento", "Peinado"],
    Rayitos: ["Matización", "Tratamiento", "Peinado"],
    Luces: ["Matización", "Tratamiento", "Peinado"],
    Mechas: ["Matización", "Tratamiento", "Peinado"],
    Permanentes: ["Tratamiento", "Peinado"],
    Alaciados: ["Tratamiento", "Peinado"],
    Manicure: ["Diseño", "Gelish", "Acrílico"],
    Pedicure: ["Diseño", "Gelish"],
    Peinados: ["Lavado", "Planchado", "Rizado"],
  },
  optionPrices: {
    Lavado: 60,
    Secado: 50,
    Peinado: 100,
    Decoloración: 200,
    Tratamiento: 150,
    Matización: 100,
    Diseño: 50,
    Gelish: 100,
    Acrílico: 200,
    Planchado: 100,
    Rizado: 150,
    "Pestañas postizas": 100,
    "Iluminación extra": 50,
  },
};

export default servicesData;
